In [109]:
import pandas as pd
import numpy as np
from sklearn.metrics import *
path_to_insults = '/Users/dattasainathd/Downloads/'
data2 = pd.read_csv(path_to_insults + 'final_train_bot.csv',na_values='0', encoding = "ISO-8859-1", nrows = 1320)
data2['no'] = 0
for x in range(0,data2.shape[0]):
    data2.loc[x, 'no']=x 
data2['Value'] = 1
data2['bot'] = 1
data2 = data2.drop('created_at', axis=1)
data2.verified=data2.verified.astype(int)
data2.default_profile=data2.default_profile.astype(int)
data2.default_profile_image=data2.default_profile_image.astype(int)
data2 = data2.drop('status', axis=1)
data2 = data2.drop('id', axis=1)
data2 = data2.drop('id_str', axis=1)
data2 = data2.drop('url', axis=1)
data2 = data2.drop('has_extended_profile', axis=1)
data2.location.fillna('', inplace=True)
data2.description.fillna('', inplace=True)
data2.followers_count.fillna(0, inplace=True)
data2.friends_count.fillna(0, inplace=True)
data2.listedcount.fillna(0, inplace=True)
data2.statuses_count.fillna(0, inplace=True)
data2.favourites_count.fillna(0, inplace=True)
data2.followers_count=data2.followers_count.astype(int)
data_description = data2['description'].str.lower()
data_name = data2['name'].str.lower()
data_screen_name = data2['screen_name'].str.lower()
bot = 'bot'
count = 0
serial = -1
for x in data_screen_name:
    serial = serial + 1
    if bot in x:
        data2.ix[serial, 'Value'] = 2
        count += 1
serial = -1
count2 = 0
for x in data_name:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count2 += 1
    except:
        pass
serial = -1
count3 = 0
for x in data_description:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count3 += 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==1):
            if(data2.loc[serial, 'statuses_count']==0 or data2.loc[serial, 'followers_count']==0 or 
               data2.loc[serial, 'friends_count']==0 ):
                data2.loc[serial, 'Value'] = 3
                count+=1
                
            
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==1):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']<12 
                and data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']<12)):
                data2.loc[serial, 'Value'] = 3
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'verified']==1):
            data2.loc[serial, 'Value'] = 3
            count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==1 or data.loc[serial, 'Value']==2):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']>10 
                or data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']>10)):
                data2.loc[serial, 'Value'] = 2
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==3):
            data2.loc[serial, 'Value'] = 0
        else:
            data2.loc[serial, 'Value'] = 1
        count+= 1
    except:
        pass
data_value = data2['Value']
datafinal = data2['bot']
print("Accuracy Score: ", (accuracy_score(datafinal, data_value)))
cnf_matrix = confusion_matrix(datafinal, data_value)
print("Confusion Matrix:")
print(cnf_matrix)


/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:106: RuntimeWarning: divide by zero encountered in double_scalars
/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:105: RuntimeWarning: invalid value encountered in double_scalars
/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:105: RuntimeWarning: divide by zero encountered in double_scalars
/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:106: RuntimeWarning: invalid value encountered in double_scalars


Accuracy Score:  0.745454545455
Confusion Matrix:
[[  0   0]
 [336 984]]


In [110]:
data3 = data2[data2.Value != 0]
data3.head(2)
data3 = data3.drop('Value', axis=1)
data3 = data3.drop('no', axis=1)

In [111]:
data3.shape

(984, 14)

In [112]:
import pandas as pd
import numpy as np
from sklearn.metrics import *
path_to_insults = '/Users/dattasainathd/Downloads/'
data2 = pd.read_csv(path_to_insults + 'final_train_nonbot.csv',na_values='0', encoding = "ISO-8859-1", nrows = 1477)

data2['no'] = 0
for x in range(0,data2.shape[0]):
    data2.loc[x, 'no']=x
print("Made a serial column which can be used for plotting purposes")  

print("Initializing two rows of Value with 0 & user with 1")
data2['Value'] = 0
data2['user'] = 1

data2 = data2.drop('created_at', axis=1)
data2.verified=data2.verified.astype(int)
data2.default_profile=data2.default_profile.astype(int)
data2.default_profile_image=data2.default_profile_image.astype(int)

data2 = data2.drop('status', axis=1)
data2 = data2.drop('id', axis=1)
data2 = data2.drop('id_str', axis=1)
data2 = data2.drop('url', axis=1)
data2 = data2.drop('has_extended_profile', axis=1)

data2.location.fillna('', inplace=True)
data2.description.fillna('', inplace=True)
data2.followers_count.fillna(0, inplace=True)
data2.friends_count.fillna(0, inplace=True)
data2.listedcount.fillna(0, inplace=True)
data2.statuses_count.fillna(0, inplace=True)
data2.favourites_count.fillna(0, inplace=True)
data2.followers_count=data2.followers_count.astype(int)
data_description = data2['description'].str.lower()
data_name = data2['name'].str.lower()
data_screen_name = data2['screen_name'].str.lower()
bot = 'bot'

print("Checking for the 'bot' word in the screen names of the accounts")
count = 0
serial = -1
for x in data_screen_name:
    serial = serial + 1
    if bot in x:
        data2.ix[serial, 'Value'] = 2
        count += 1
serial = -1

print("No.of accounts which had 'bot' in screen name: ", count)
print("accuracy", count/data2.shape[0])

print("Checking for the 'bot' word in the names of the accounts")
count2 = 0
for x in data_name:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count2 += 1
    except:
        pass
print("No.of accounts which had 'bot' in names: ", count2)
print("accuracy", count2/data2.shape[0])
serial = -1
print("Checking for the 'bot' word in the description of the accounts")
count3 = 0
for x in data_description:
    serial = serial + 1
    try:
        if bot in x:
            data2.ix[serial, 'Value'] = 2
            count3 += 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==0):
            if(data2.loc[serial, 'statuses_count']==0 or data2.loc[serial, 'followers_count']==0 or 
               data2.loc[serial, 'friends_count']==0 ):
                data2.loc[serial, 'Value'] = 3
                count+=1
                
            
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==0):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']<12 
                or data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']<12)):
                data2.loc[serial, 'Value'] = 3
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'verified']==1):
            data2.loc[serial, 'Value'] = 3
            count+= 1
    except:
        pass
print("trying to filter accounts which are verified all the verified user accounts are humans")
print("twitter user accounts which are verified are assigned to value 3")
print("total no. of verified users:", count)
print("accuracy", count/data2.shape[0])
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==1 or data.loc[serial, 'Value']==0):
            if((data2.loc[serial, 'statuses_count']/data2.loc[serial, 'followers_count']>10 
                or data2.loc[serial, 'statuses_count']/data2.loc[serial, 'friends_count']>10)):
                data2.loc[serial, 'Value'] = 2
                count+= 1
    except:
        pass
serial = -1
count = 0
unnec = []
for x in range(0, data2.shape[0]):
    try:
        serial = serial + 1
        if(data2.loc[serial, 'Value']==2):
            data2.loc[serial, 'Value'] = 0
        else:
            data2.loc[serial, 'Value'] = 1
        count+= 1
    except:
        pass
data_value = data2['Value']
datafinal = data2['user']
print("Accuracy Score: ", (accuracy_score(datafinal, data_value)))
cnf_matrix = confusion_matrix(datafinal, data_value)
print("Confusion Matrix:")
print(cnf_matrix)


Made a serial column which can be used for plotting purposes
Initializing two rows of Value with 0 & user with 1
Checking for the 'bot' word in the screen names of the accounts
No.of accounts which had 'bot' in screen name:  10
accuracy 0.006775067750677507
Checking for the 'bot' word in the names of the accounts
No.of accounts which had 'bot' in names:  7
accuracy 0.0047425474254742545
Checking for the 'bot' word in the description of the accounts
trying to filter accounts which are verified all the verified user accounts are humans
twitter user accounts which are verified are assigned to value 3
total no. of verified users: 645
accuracy 0.4369918699186992


/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:127: RuntimeWarning: divide by zero encountered in double_scalars


Accuracy Score:  0.575880758808
Confusion Matrix:
[[  0   0]
 [626 850]]


/Users/dattasainathd/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:126: RuntimeWarning: divide by zero encountered in double_scalars


In [113]:
data2 = data2.drop('Value', axis=1)
data2 = data2.drop('no', axis=1)
data2 = data2.drop('user', axis=1)
data2['bot'] = 0

In [114]:
data2.shape

(1476, 14)

In [115]:
result = pd.concat([data3, data2], ignore_index=True)

In [116]:
result

screen_name                        location  \
0     "HoustonPokeMap"                   "Houston, TX"   
1            kernyeahx       Templeville town, MD, USA   
2      mattlieberisbot                                   
3         lucarivera16           Dublin, United States   
4       dantheimprover                      Austin, TX   
5          _all_of_us_                   in a machine.   
6        KatamariItems                                   
7      AutophagyPapers                                   
8           HSC_papers                                   
9          everycheese                     cheese land   
10          gyr_papers                                   
11        hard_to_yelp                                   
12     fuckeverywordza                                   
13     yeahTonyaGonzal                  Pensacola, USA   
14     ecin_gnihtaseod                                   
15      onetruewiseman                         AMERICA   
16       everycolorbot             the RGB color space   
17        himawari8bot                           Space   
18        emoji__polls                  ‰÷•ü   
19     everytrolltroll                                   
20            hyphizer                        #botALLY   
21       GreenwadeGema                                   
22          par_papers                                   
23     assembly_papers                                   
24       DeepDreamThis                 London, England   
25     dstroyeveryword                                   
26     snowcloneminute                                   
27       NESGarbageBot                                   
28      BklynMuseumBot                    Brooklyn, NY   
29          clitoscope                                   
...                ...                             ...   
2430       cesarmillan                 Los Angeles, CA   
2431       mayauofa213                      Tucson, AZ   
2432              Andy       íìT: 40.735225,-74.006791   
2433      "VicenteTao"                              ""   
2434           kar2905        Santa Monica, California   
2435         palalablo                                   
2436       dutt_ashish                Bangalore, India   
2437      KellerSeason                                   
2438       VitorBecker                          Santos   
2439      honorsociety                 Los Angeles, CA   
2440    brian_littrell  Some where over the rainbow :)   
2441      TomJackson57                                   
2442          visu_bio               www.mnrindia.org    
2443      VivianePatty           Brasil/Rio de Janeiro   
2444      mohsin_shk11                   Mumbai, India   
2445         Robbie_OC                                   
2446     MiThiicSource                          Canada   
2447       "JTJ_Photo"     "Washington, DC Metro Area"   
2448          SkillzVa                       Worldwide   
2449        iamadityar                    New York, NY   
2450     haileybaldwin                      East Coast   
2451         ahmadriaz                                   
2452      thetrickisto                    Brooklyn, NY   
2453           OKKenna                  info@kenna.com   
2454       MixologyBot                                   
2455     leslieberland                                   
2456      SamuelsPants                     brooklyn NY   
2457       jimmyfallon              New York, New York   
2458    LocalAlligator         England, United Kingdom   
2459      RepJoeBarton                       Ennis, TX   

                                            description  followers_count  \
0     "Rare and strong PokŽmon in Houston, TX. See ...             1291   
1     From late 2014 Socium Marketplace will make sh...                1   
2     Inspired by the smart, funny folks at @replyal...             1086   
3                Inspiring cooks everywhere since 1956.               11   
4     Just a guy trying to do good

In [117]:
#NOW THE TRAINING ACCURACY BEGINS
data = result
data['Value'] = 0
data_description = data['description'].str.lower()
data_name = data['name'].str.lower()
data_screen_name = data['screen_name'].str.lower()
bot = 'bot'
serial = -1

for x in data_screen_name:
    serial = serial + 1
    if bot in x:
        data.ix[serial, 'Value'] = 1
        
serial = -1

for x in data_name:
    serial = serial + 1
    try:
        if bot in x:
            data.ix[serial, 'Value'] = 1
    except:
        pass

serial = -1

for x in data_description:
    serial = serial + 1
    try:
        if bot in x:
            data.ix[serial, 'Value'] = 1
    except:
        pass

In [118]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==0):
            if(data.loc[serial, 'statuses_count']==0 or data.loc[serial, 'followers_count']==0 or 
               data.loc[serial, 'friends_count']==0 ):
                data.loc[serial, 'Value'] = 2
                count+=1
    except:
        pass
count

154

In [119]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==0):
            if((data.loc[serial, 'statuses_count']/data.loc[serial, 'followers_count']<12 
                and data.loc[serial, 'statuses_count']/data.loc[serial, 'friends_count']<12)):
                data.loc[serial, 'Value'] = 2
                count+= 1
    except:
        pass
count

902

In [120]:
#trying to filter accounts which are verified all the verified user accounts are humans
#because twitter verifies users only 
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'verified']==1):
            data.loc[serial, 'Value'] = 2
            count+= 1
    except:
        pass
count

647

In [121]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']==0):
            if((data.loc[serial, 'statuses_count']/data.loc[serial, 'followers_count']>10 
                or data.loc[serial, 'statuses_count']/data.loc[serial, 'friends_count']>10)):
                data.loc[serial, 'Value'] = 1
                count+= 1
    except:
        pass
count

571

In [122]:
serial = -1
count = 0
unnec = []
for x in range(0, data.shape[0]):
    try:
        serial = serial + 1
        if(data.loc[serial, 'Value']!=1):
            data.loc[serial, 'Value'] = 0
            count+= 1
    except:
        pass
count

1378

In [123]:
data_value = data['Value']
datafinal = data['bot']


print("Accuracy Score: ", (accuracy_score(datafinal, data_value)))
cnf_matrix = confusion_matrix(datafinal, data_value)
print("Confusion Matrix:")
print(cnf_matrix)

Accuracy Score:  0.847154471545
Confusion Matrix:
[[1239  237]
 [ 139  845]]


In [132]:
print("Precision Score: ", (precision_score(datafinal, data_value)))
print("Recall Score: ", (recall_score(datafinal, data_value)))
print("f1 Score: ", (f1_score(datafinal, data_value)))
print("ROC AUC Score: ", (roc_auc_score(datafinal, data_value)))
print("Mean Squared Error: ", (mean_squared_error(datafinal, data_value)))

Precision Score:  0.780961182994
Recall Score:  0.858739837398
f1 Score:  0.818005808325
ROC AUC Score:  0.849085365854
Mean Squared Error:  0.152845528455


In [135]:
fpr, tpr, thresholds = roc_curve(datafinal, data_value)

In [136]:
fpr

array([ 0.        ,  0.16056911,  1.        ])

In [137]:
tpr

array([ 0.        ,  0.85873984,  1.        ])

In [ ]:
neg_mean_squared_error